### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by KingAndroid** [markolazic88/SwipeCardView#3] opened 2017-11-23 08:08 UTC
If we use it using package manager, we will get this issue.
```error
System.TypeLoadException: Could not resolve type with token 01000030 (from typeref, class/assembly Xamarin.Forms.Internals.ResourceLoader, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by markolazic88** [comment] 2017-11-28 13:28
It seems that this issue occurs when you are referencing multiple versions of the same library.  For more info read [here](https://stackoverflow.com/questions/41163887/could-not-resolve-type-with-token-0100000f/42511504#42511504). 
If I would have to guess, you had multiple versions of Xamarin Forms referenced, possibly because SwipeCardView uses version 2.3.4.224, while you are referencing 2.3.5 from your code.

I just updated SwipeCardView to reference Xamarin Forms 2.5.0.91635 and packed it in version 1.1.0.  You can find the new package at https://www.nuget.org/packages/MLToolkit.Forms.SwipeCardView/1.1.0

**Comment by markolazic88** [comment] 2018-11-29 23:54
Most likely this issue was not related to the library directly. I am closing the issue since I was never able to reproduce it, and because SwipeCardView is referencing Xamarin.Forms 3.0 now.

**Closed as completed by markolazic88** 2018-11-29 23:54 UTC
